QuestSite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conferences.urls')),
    path('conferences/', include('conferences.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conferences/urls.py
from django.urls import path
from conferences import views

urlpatterns = [
    path('', views.conferences_home, name='conferences_home'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.ConfDetailView.as_view(), name='conf_detail'),
    path('<int:pk>/edit', views.ConfEditView.as_view(), name='conf_edit'),
    path('<int:pk>/delete', views.ConfDeleteView.as_view(), name='conf_delete')
]

conferences/models.py
from django.db import models
from django_countries.fields import CountryField


class Conference(models.Model):
    title = models.CharField('Title', max_length=255)
    date = models.DateTimeField('Date')
    lat = models.FloatField('Latitude', max_length=50)
    lng = models.FloatField('Longitude', max_length=50)
    country = CountryField(blank_label='Country')
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/conferences/{self.id}'
    

conferences/forms.py
from .models import Conference
from django.forms import ModelForm, TextInput, DateTimeInput
from django import forms
from django_countries.widgets import CountrySelectWidget


class ConferenceForm(ModelForm):
    class Meta:
        model = Conference
        fields = ['title', 'date', 'lat', 'lng', 'country']
        
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Title',
            }),
            'date': DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Date',
                'type': 'datetime-local',
            }),
            'lat': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Latitude',
            }),
            'lng': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Longitude',
            }),
        }
        

conferences/views.py
from django.shortcuts import render, redirect
from .models import Conference
from .forms import ConferenceForm
from django.views.generic import DetailView, UpdateView, DeleteView


def conferences_home(request):
    conferences = Conference.objects.all()
    return render(request, 'conferences/conferences_home.html', {'conferences': conferences})


# Класс динамической страницы
class ConfDetailView(DetailView):
    model = Conference
    template_name = 'conferences/details_view.html'  # Шаблон обработки страницы
    context_object_name = 'objectkey'    # Ключ по которому передается объект
    

# Класс динамической страницы для редактирования
class ConfEditView(UpdateView):
    model = Conference
    template_name = 'conferences/create.html'
    form_class = ConferenceForm
    
    
# Класс динамической страницы для удаления
class ConfDeleteView(DeleteView):
    model = Conference
    success_url = '/conferences/'
    template_name = 'conferences/conf_delete.html'


def create(request):
    error = ''
    if request.method == 'POST':
        form = ConferenceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('conferences_home')
        else:
            error = 'Not correct format'
    # Новый объект 
    form = ConferenceForm()
    # Словарь для передачи в шаблон 
    data = {
        'form': form,
        'error': error,
    }
    return render(request, 'conferences/create.html', data)

conferences/templates/conferences/conf_delete.html
{% extends 'conferences/layout.html' %}

{% block title %}Delete conf{% endblock %}
    
{% block content %}
    <div class="features" enctype="multipart/form-data">
        <h1>Delete conference</h1>
        <form method="post">
            {% csrf_token %}
            <button class="button2 button-new" type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

conferences/templates/conferences/conferences_home.html
{% extends 'conferences/layout.html' %}

{% block title %}Our conferences{% endblock %}
    
{% block content %}
    <div class="features">
        <h1>Our conferences</h1>
        {% for items in conferences %}
            <div class="alert alert-secondary">
                <h3>{{ items.title }}</h3>
                <p>{{ items.date }}</p>
                <a href="{% url 'conf_detail' items.id %}" class="button2 button-new">More...</a>
            </div>
        {% endfor %}
{% endblock %}

conferences/templates/conferences/create.html
{% extends 'conferences/layout.html' %}

{% block title %}Create conference{% endblock %}
    
{% block content %}
    <div class="features" enctype="multipart/form-data">
        <h1>New conference</h1>
        <form method="post" id='form'>
            {% csrf_token %}
            {{ form.title }}<br>
            {{ form.date }}<br>
            <input type="text" name="lat" class="form-control" placeholder="Latitude" required="" id="id_lat">
            <input type="text" name="lng" class="form-control" placeholder="Longitude" required="" id="id_lng">
            <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=initMap&v=weekly"defer></script>
            <div style="padding:10px">
                <div id="map"></div>
            </div>
            <script type="text/javascript">
                var map;
                var marker = null;
                function initMap() {							
                    var latitude = 47.795682767721175;
                    var longitude = 35.18219198436859;
                    
                    var myLatLng = {lat: latitude, lng: longitude};
                    
                    map = new google.maps.Map(document.getElementById('map'), {
                      center: myLatLng,
                      zoom: 4,
                      disableDoubleClickZoom: true, // disable the default map zoom on double click
                    });
                    
                    // Update lat/long value of div when anywhere in the map is clicked	
                    google.maps.event.addListener(map,'click',function(event) {				
                        document.getElementById('latclicked').innerHTML = event.latLng.lat();
                        document.getElementById('longclicked').innerHTML =  event.latLng.lng();
                    });

                    // Create new marker on double click event on the map
                    google.maps.event.addListener(map,'dblclick',function(event) {
                        var marker = new google.maps.Marker({
                          position: event.latLng, 
                          map: map, 
                          title: event.latLng.lat()+', '+event.latLng.lng()
                        });
                        
                        // Update lat/long value of div when the marker is clicked
                        marker.addListener('click', function() {
                          document.getElementById('latclicked').innerHTML = event.latLng.lat();
                          document.getElementById('longclicked').innerHTML =  event.latLng.lng();
                        });
                    });
                }
            </script>
            <style type="text/css">
                #map {
                    position: relative;
                    bottom: 24px;
                    left: -20px;
                    height: 350px;
                    width: 500px;
                    margin-top: 0px;
                    margin-bottom: 10px;
                }
            </style>
            {{ form.country }}
            <span>{{ error }}</span>
            <button class="button2 button-new" type="submit">Create</button>
            <div id="latclicked"></div>
		    <div id="longclicked"></div>
        </form>
    </div>
{% endblock %}

conferences/templates/conferences/details_view.html
{% extends 'conferences/layout.html' %}

{% block title %}{{ objectkey.title }}{% endblock %}
    
{% block content %}
    <div class="features1">
        <h1>{{ objectkey.title }}</h1>
        <h2>
            <span style="font-size:25px; color:rgb(168, 168, 233); text-transform:capitalize;">
                Date:
            </span>
            <span style="font-size:25px; text-transform:capitalize;">
                {{ objectkey.date }}
            </span>
        </h2>
        <h2>
            <span style="font-size:25px; color:rgb(168, 168, 233); text-transform:capitalize;">
                Latitude:
            </span>
            <span style="font-size:25px; text-transform:capitalize;">
                {{ objectkey.lat }}
            </span>
        </h2>
        <h2>
            <span style="font-size:25px; color:rgb(168, 168, 233); text-transform:capitalize;">
                Longitude:
            </span>
            <span style="font-size:25px; text-transform:capitalize;">
                {{ objectkey.lng }}
            </span>
        </h2>
        <div id="map"></div>
            <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=initMap&v=weekly"defer></script>
            <script>
                let map;
                function initMap(){
                    lat = parseFloat({{ objectkey.lat }});
                    lng = parseFloat({{ objectkey.lng }});
                    const myLatLng = {lat: lat, lng: lng};
                    map = new google.maps.Map(document.getElementById("map"), {
                        center: myLatLng,
                        zoom: 8,
                    });
                    new google.maps.Marker({
                        position: myLatLng,
                        map,
                        title: "{{ objectkey.country }}",
                    });
                }
                window.initMap = initMap;
            </script>
            <style type="text/css">
                #map {
                    position: relative;
                    bottom: -5px;
                    left: -6px;
                    height: 350px;
                    width: 500px;
                    margin-top: 0px;
                    margin-bottom: 10px;
                }
            </style>
        <h2>
            <span style="font-size:25px; color:rgb(168, 168, 233); text-transform:capitalize;">
                Country:
            </span>
            <span style="font-size:25px; text-transform:capitalize;">
                {{ objectkey.country }}
            </span>
        </h2>
        <a href="{% url 'conf_edit' objectkey.id %}" class="button2 button-new">Edit</a>
        <a href="{% url 'conf_delete' objectkey.id %}" class="button2 button-new">Delete</a>
    </div>
{% endblock %}

conferences/templates/conferences/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <script src="https://kit.fontawesome.com/0f1a2fa745.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="intro" id="intro">
        <script src="{% static 'main/js/three.min.js' %}"></script>
        <script src="{% static 'main/js/vanta.rings.min.js' %}"></script>
        <script>
            VANTA.RINGS({
            el: "#intro",
            mouseControls: true,
            touchControls: true,
            gyroControls: false,
            minHeight: 200.00,
            minWidth: 200.00,
            scale: 1.00,
            scaleMobile: 1.00
            })
            </script>
        <aside>
            <img src="{% static 'main/img/logoimg.png' %}" alt="logotype">  
            <span class="logo">SpaceConf</span> 
        </aside>
        <a href="{% url 'create' %}"><li><button class="button1 button-new">Create</button></li></a>
        <a href="{% url 'conferences_home' %}"><li><button class="button1 button-new">Home</button></li></a>
        {% block content %}
        {% endblock %}
    </div>
    <div class="wrapper">
        <div class="push"></div>
    </div>
        <div class="footer"></div>
    </div>
</body>
</html>